openapi: 3.1.0
info:
  title: ZTNet Organization Network Rest API
  version: 1.0.0
  description: |
    Access the ZTNet Organization suite through our RESTful Web API, compatible with version 0.6.0 and beyond. 
    
    This interface is subject to a rate limit of 50 requests per minute to ensure service reliability.

servers:
  - url: https://ztnet.network/api/v1
    description: ZTNet Organization API
    variables:
      version:
        default: v1
        description: API version

paths:
  /org/:orgid/network:
    get:
      summary: Returns a list of Networks in the Organization you have access to
      description: |
        Returns an array of Networks you have access to.
      operationId: getUserNetworks
      parameters:
        - name: x-ztnet-auth
          in: header
          required: true
          schema:
            type: string
          description: API Key for the user
        - name: orgid
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the organization
      responses:
        200:
          description: An array of Network IDs
          content:
            application/json:
              schema:
                $ref: '../../_schema/NetworkSchema.yml#/NetworkResponse'
              example:
                $ref: '../../_example/NetworkExample.yml#/NetworkArrayExample'
        401:
          $ref: '../../_http_responses/Unauthorized.yml#/Unauthorized'
        429:
          $ref: '../../_http_responses/RateLimitExceeded.yml#/RateLimitExceeded'
        500:
          $ref: '../../_http_responses/InternalServerError.yml#/InternalServerError'

    # POST /network
    post:
      summary: Create New Network within the Organization
      operationId: createNewNetwork
      parameters:
        - name: x-ztnet-auth
          in: header
          required: true
          schema:
            type: string
          description: API Key for the user
        - name: orgid
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the organization
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              # required:
              #   - name
              properties:
                name:
                  type:
                    - string
                  required: false
                  description: Name of the network. If not provided, a random name will be generated.
      responses:
        200:
          description: New Network Created
          content:
            application/json:
              schema:
                $ref: '../../_schema/NetworkSchema.yml#/NetworkResponse'
              example:
                $ref: '../../_example/NetworkExample.yml#/NetworkExample'
                
        401:
          $ref: '../../_http_responses/Unauthorized.yml#/Unauthorized'
        429:
          $ref: '../../_http_responses/RateLimitExceeded.yml#/RateLimitExceeded'
        500:
          $ref: '../../_http_responses/InternalServerError.yml#/InternalServerError'

  /org/:orgid/network/{networkId}:
    get:
      summary: Returns information about a specific organization network
      operationId: getNetworkInfo
      parameters:
        - name: x-ztnet-auth
          in: header
          required: true
          schema:
            type: string
          description: API Key for the user
        - name: networkId
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the network
        - name: orgid
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the organization
      responses:
        200:
          description: Detailed information of the specified Network
          content:
            application/json:
              schema:
                $ref: '../../_schema/NetworkSchema.yml#/NetworkResponse'
              example:
                $ref: '../../_example/NetworkExample.yml#/NetworkExample'
        401:
          $ref: '../../_http_responses/Unauthorized.yml#/Unauthorized'
        429:
          $ref: '../../_http_responses/RateLimitExceeded.yml#/RateLimitExceeded'
        500:
          $ref: '../../_http_responses/InternalServerError.yml#/InternalServerError'
    post:
      summary: Update a specific organization network
      operationId: updateNetworkInfo
      parameters:
        - name: x-ztnet-auth
          in: header
          required: true
          schema:
            type: string
          description: API Key for the user
        - name: networkId
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the network
        - name: orgid
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the organization
      requestBody:
        required: false
        description: Each field is optional. Only the fields that are provided will be updated.
        content:
          application/json:
            schema:
              $ref: '../../_schema/NetworkSchema.yml#/UpdateNetworkShema'
      responses:
        200:
          description: Network Updated
          content:
            application/json:
              schema:
                $ref: '../../_schema/NetworkSchema.yml#/NetworkResponse'
              example:
                $ref: '../../_example/NetworkExample.yml#/NetworkExample'
        401:
          $ref: '../../_http_responses/Unauthorized.yml#/Unauthorized'
        429:
          $ref: '../../_http_responses/RateLimitExceeded.yml#/RateLimitExceeded'
        500:
          $ref: '../../_http_responses/InternalServerError.yml#/InternalServerError'

