openapi: 3.0.3
info:
  title: ZTNet Organization Network Member Rest API
  version: 1.0.0
  description: |
    Access the ZTNet Organization suite through our RESTful Web API. 
    
    This interface is subject to a rate limit of 50 requests per minute to ensure service reliability.

servers:
  - url: https://ztnet.network/api/v1
    description: ZTNet API
        
components:
  securitySchemes:
    x-ztnet-auth:
      type: apiKey
      in: header
      name: x-ztnet-auth
      description: API key required for access

security:
  - x-ztnet-auth: []
paths:                 
  /org/:orgid/network/{networkId}/member:
    get:
      summary: Returns a list of Members in a organization network
      operationId: getNetworkMemberInfo
      parameters:
        - name: networkId
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the network
        - name: orgid
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the organization
      responses:
        200:
          description: Detailed information of the specified organization Network Member
          content:
            application/json:
              schema:
                $ref: '../../_schema/NetworkMemberSchema.yml#/NetworkMemberResponse'
              example:
                $ref: '../../_example/NetworkMemberExample.yml#/NetworkArrayMemberExample'
        401:
          $ref: '../../_http_responses/Unauthorized.yml#/Unauthorized'
        429:
          $ref: '../../_http_responses/RateLimitExceeded.yml#/RateLimitExceeded'
        500:
          $ref: '../../_http_responses/InternalServerError.yml#/InternalServerError'

  /org/:orgid/network/{networkId}/member/{memberId}:
    get:
      summary: Returns a specific organization network member
      operationId: getNetworkMemberByIdInfo
      parameters:
        - name: networkId
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the network
        - name: memberId
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the member
        - name: orgid
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the organization
      responses:
        200:
          description: Detailed information of the specified organization Network Member
          content:
            application/json:
              schema:
                $ref: '../../_schema/NetworkMemberSchema.yml#/NetworkMemberResponse'
              example:
                $ref: '../../_example/NetworkMemberExample.yml#/NetworkArrayMemberExample'
        401:
          $ref: '../../_http_responses/Unauthorized.yml#/Unauthorized'
        429:
          $ref: '../../_http_responses/RateLimitExceeded.yml#/RateLimitExceeded'
        500:
          $ref: '../../_http_responses/InternalServerError.yml#/InternalServerError'

    post:
      summary: Modify a organization network member
      description: |
        Modify a organization network member. This endpoint can also be used to pre-authorize a member that has not yet joined the network by providing their ZeroTier node ID as the `memberId`. If the member does not yet exist in the database, it will be created on the ZeroTier controller and returned in the response.
      parameters:
        - in: path
          name: networkId
          required: true
          schema:
            type: string
          description: ID of the network
        - in: path
          name: memberId
          required: true
          schema:
            type: string
          description: ID of the member
        - name: orgid
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the organization
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: User defined name of the member
                authorized:
                  type: boolean
                  description: Authorization status of the member
              # required:
              #   - name
              #   - authorized
              example:
                name: "John Doe"
                authorized: "false"
      responses:
        200:
          description: Detailed information of the specified Network Member
          content:
            application/json:
              schema:
                $ref: '../../_schema/NetworkMemberSchema.yml#/NetworkMemberResponse'
              example:
                $ref: '../../_example/NetworkMemberExample.yml#/NetworkArrayMemberExample'
        401:
          $ref: '../../_http_responses/Unauthorized.yml#/Unauthorized'
        429:
          $ref: '../../_http_responses/RateLimitExceeded.yml#/RateLimitExceeded'
        500:
          $ref: '../../_http_responses/InternalServerError.yml#/InternalServerError'

    delete:
      summary: Delete a organization network member
      description: This action flags the member as deleted, revokes their authorization, and updates their status in the database. Consequently, the member will be moved to the "Stashed Members" list, indicating their altered status.
      operationId: deleteNetworkMember
      parameters:
        - in: path
          name: networkId
          required: true
          schema:
            type: string
          description: ID of the network
        - in: path
          name: memberId
          required: true
          schema:
            type: string
          description: ID of the member
        - name: orgid
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the organization
      responses:
        200:
          description: Organization Network Response
          content:
            application/json:
              schema:
                $ref: '../../_schema/NetworkSchema.yml#/NetworkResponse'
              example:
                $ref: '../../_example/NetworkExample.yml#/NetworkArrayExample'
        401:
          $ref: '../../_http_responses/Unauthorized.yml#/Unauthorized'
        429:
          $ref: '../../_http_responses/RateLimitExceeded.yml#/RateLimitExceeded'
        500:
          $ref: '../../_http_responses/InternalServerError.yml#/InternalServerError'