-- AlterTable
ALTER TABLE "GlobalOptions" ADD COLUMN     "email" TEXT,
ADD COLUMN     "ignoreTLS" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "password" TEXT,
ADD COLUMN     "requireTLS" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "secure" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "smtpHost" TEXT,
ADD COLUMN     "smtpPort" TEXT NOT NULL DEFAULT '587',
ADD COLUMN     "useSSL" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "username" TEXT;
