openapi: 3.1.0
info:
  title: ZTNet Network Rest API
  version: 1.0.0
  description: |
    Access the ZTNet suite through our RESTful Web API, compatible with version 0.4.0 and beyond. 
    
    This interface is subject to a rate limit of 50 requests per minute to ensure service reliability.

servers:
  - url: https://ztnet.network/api/v1
    description: ZTNet API
    variables:
      version:
        default: v1
        description: API version

paths:                 
  /network/{networkId}/member:
    get:
      summary: Return an individual member on a network
      operationId: getNetworkMemberInfo
      parameters:
        - name: x-ztnet-auth
          in: header
          required: true
          schema:
            type: string
          description: API Key for the user
        - name: networkId
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the network
      responses:
        200:
          description: Detailed information of the specified Network Member
          content:
            application/json:
              schema:
                $ref: '../_schema/NetworkMemberResponse.yml#/NetworkMemberResponse'
              example:
                $ref: '../_example/NetworkMemberExample.yml#/NetworkMemberExample'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        429:
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
