openapi: 3.1.0
info:
  title: ZTNet Web API
  info_path: restapi/ztnet-web-api
  version: 1.0.0
  description: |
    Public API for ZTNet. Available from ztnet version 0.4.0 onwards.
    
    This API is rate-limited to 50 requests per minute
paths:
  /network:
    get:
      summary: Returns a list of Networks you have access to
      operationId: getUserNetworks
      parameters:
        - name: x-ztnet-auth
          in: header
          required: true
          schema:
            type: string
          description: API Key for the user
      responses:
        200:
          description: An array of Network IDs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
              examples:
                example1:
                  value: ["networkid#1", "networkid#2"]
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        429:
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    # POST /network
    post:
      summary: Create New Network
      operationId: createNewNetwork
      parameters:
        - name: x-ztnet-auth
          in: header
          required: true
          schema:
            type: string
          description: API Key for the user
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              # required:
              #   - name
              properties:
                name:
                  type:
                    - string
                  required: false
                  description: Name of the network. If not provided, a random name will be generated.
      responses:
        200:
          description: New Network Created
          content:
            application/json:
              schema:
                $ref: '../_schema/NetworkResponse.yml#/NetworkResponse'
              example:
                $ref: '../_example/NetworkExample.yml'
                
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        429:
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
