name: General Support Request
description: General support request for Next Ztnet
title: "[Support]: "
labels: ["support", "triage"]
# assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the problem you are having
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Use docker image tag or git commit hash
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - Debian
        - Ubuntu
        - Other Linux
        - Windows
        - Other
    validations:
      required: false
  - type: textarea
    id: other
    attributes:
      label: Any other information that may be helpful
