name: Support Request
description: General support request for ZTNET
title: "[Support]: "
labels: ["support"]

body:
  - type: textarea
    id: description
    attributes:
      label: "📝 Describe the Problem You Are Having"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: "🔖 Version"
      description: "Please provide the docker image tag or git commit hash you're using."
    validations:
      required: true
  - type: textarea
    id: docker-logs
    attributes:
      label: "📋 Docker Logs"
      description: "Please include Docker logs. Run `docker logs ztnet` and copy and paste the output here. This will be automatically formatted into code, so no need for backticks."
      render: shell
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: "💻 Operating System"
      options:
        - Debian
        - Ubuntu
        - Other Linux
        - Windows
        - Other
    validations:
      required: false
  - type: textarea
    id: other
    attributes:
      label: "📚 Any Other Information That May Be Helpful"
