name: Support Request
description: Use this template for seeking assistance with Next Ztnet
title: "[Support]: "
labels: ["support"]
assignees: []
body:
  - type: markdown
    id: instructions
    attributes:
      value: "## Please complete the following sections to help us better understand your issue.\n"

  - type: textarea
    id: description
    attributes:
      label: "🔍 Problem Description"
      description: "Please describe the problem you're facing in detail, including steps to reproduce it, if possible."
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: "🔖 Version"
      description: "Kindly provide the version number of the Next ztnet that you are currently using. You can locate this information at the bottom of the 'Network' page."
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: "💻 Operating System"
      description: "Please select the operating system you are using."
      options:
        - Ubuntu
        - Debian
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "📜 Logs"
      description: "If applicable, include any relevant logs or error messages. Please use code blocks (```) to format your logs."
    validations:
      required: false

  - type: textarea
    id: other
    attributes:
      label: "📝 Additional Context"
      description: "Please provide any other information that may be helpful for troubleshooting, such as network configurations, hardware specs, etc."
    validations:
      required: false
