openapi: 3.1.0
info:
  title: ZTNet Network Rest API
  version: 1.0.0
  description: |
    Access the ZTNet suite through our RESTful Web API, compatible with version 0.4.0 and beyond. 
    
    This interface is subject to a rate limit of 50 requests per minute to ensure service reliability.

servers:
  - url: https://ztnet.network/api/v1
    description: ZTNet API
    variables:
      version:
        default: v1
        description: API version

paths:                 
  /network/{networkId}/member:
    get:
      summary: Returns a list of Members on the network
      operationId: getNetworkMemberInfo
      parameters:
        - name: x-ztnet-auth
          in: header
          required: true
          schema:
            type: string
          description: API Key for the user
        - name: networkId
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the network
      responses:
        200:
          description: Detailed information of the specified Network Member
          content:
            application/json:
              schema:
                $ref: '../../_schema/NetworkMemberResponse.yml#/NetworkMemberResponse'
              example:
                $ref: '../../_example/NetworkMemberExample.yml#/NetworkArrayMemberExample'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        429:
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /network/{networkId}/member/{memberId}:
    post:
      summary: Modify a network member
      description: Modify a network member
      parameters:
        - in: path
          name: networkId
          required: true
          schema:
            type: string
          description: ID of the network
        - in: path
          name: memberId
          required: true
          schema:
            type: string
          description: ID of the member
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: User defined name of the member
                authorized:
                  type: boolean
                  description: Authorization status of the member
              # required:
              #   - name
              #   - authorized
              example:
                name: "John Doe"
                authorized: "false"
      responses:
        200:
          description: Detailed information of the specified Network Member
          content:
            application/json:
              schema:
                $ref: '../../_schema/NetworkMemberResponse.yml#/NetworkMemberResponse'
              example:
                $ref: '../../_example/NetworkMemberExample.yml#/NetworkArrayMemberExample'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        429:
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    delete:
      summary: Delete a network member
      # description: Delete a network member
      operationId: deleteNetworkMember
      parameters:
        - in: path
          name: networkId
          required: true
          schema:
            type: string
          description: ID of the network
        - in: path
          name: memberId
          required: true
          schema:
            type: string
          description: ID of the member
      responses:
        200:
          description: Network Response
          content:
            application/json:
              schema:
                $ref: '../../_schema/NetworkResponse.yml#/NetworkResponse'
              example:
                $ref: '../../_example/NetworkExample.yml#/NetworkArrayExample'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        429:
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string