FROM node:18-bullseye-slim
WORKDIR /app

COPY . .

ENV NODE_ENV development
RUN apt update && apt install -y git curl sudo postgresql-client procps nano

RUN chmod +x .devcontainer/init-cmd.sh

# USER nextjs

EXPOSE 3000

ENV PORT 3000
ENTRYPOINT ["/app/.devcontainer/init-cmd.sh"]