FROM node:22.1-bookworm-slim

ENV NODE_ENV development
RUN apt update && apt install -y git curl sudo postgresql-client procps nano

# RUN chmod +x .devcontainer/init-cmd.sh

# USER nextjs

# expose port 3000 for application and 5555 for prisma studio
EXPOSE 3000 5555

ENV PORT 3000
ENTRYPOINT ["/workspaces/.devcontainer/init-cmd.sh"]
