upstream backend {
    server api:4000; #node app address
}


server {
    listen       80;
    server_name  143.198.112.122;
  
    location / {
        root   /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location /api {
        rewrite /api/(.*) /$1 break;
        proxy_pass http://backend;
    }

    #error_page  404              /404.html;
    location /refresh_token {
            proxy_pass http://backend;
    }
    location /logout {
            proxy_pass http://backend;
    }
    location /graphQl {
            proxy_pass http://backend;
    }

    location ~* \.io {
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_set_header X-NginX-Proxy false;

            proxy_pass  http://backend;
            proxy_redirect off;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
    }
    location ^~ /subscription {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $http_host;
                proxy_set_header X-NginX-Proxy false;

                proxy_pass  http://backend;
                proxy_redirect off;

                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
        }
    location ^~ /asset {
        proxy_pass http://backend;
    }

    location ^~ /controller {
        proxy_pass http://backend;
    }
}