
# map $http_upgrade $connection_upgrade {
#     ''         close;
#     default    upgrade;
# }
upstream client {
    server client:3000; #react app address
}

upstream backend {
    server api:4000; #node app address
}


server {
    listen       80;
    # server_name  localhost;

    #access_log  /var/log/nginx/host.access.log  main;
    location / {
        proxy_pass http://client;
    }

    location /sockjs-node {
        proxy_pass http://client;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }
    
    location /api {
        rewrite /api/(.*) /$1 break;
        proxy_pass http://backend;
    }

    # location / {
    #     root   /usr/share/nginx/html;
    #     index  index.html index.htm;
    # }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    # error_page   500 502 503 504  /50x.html;
    # location = /50x.html {
    #     root   /usr/share/nginx/html;
    # }
    # location ^~ /api/ {
    #         proxy_pass http://backend;
    # }
    location /refresh_token {
            proxy_pass http://backend;
    }
    location /logout {
            proxy_pass http://backend;
    }
    location /graphQl {
            proxy_pass http://backend;
    }

    location ~* \.io {
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_set_header X-NginX-Proxy false;

            proxy_pass  http://backend;
            proxy_redirect off;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
    }
    location ^~ /subscription {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $http_host;
                proxy_set_header X-NginX-Proxy false;

                proxy_pass  http://backend;
                proxy_redirect off;

                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
        }
    location ^~ /asset {
        proxy_pass http://backend;
    }

    location ^~ /controller {
        proxy_pass http://backend;
    }
}