theme: jekyll-theme-slate
title: ztnet
tagline: User interface for self hosted zerotier network controller.
description: Host your own private VPN controller using ztnet. This application provides a user interface built on top of zerotier-one.
author: Bernt Christian Egeland
url: https://sinamics.github.io/ztnet/
twitter:
  username: BerntChris
  card: summary_large_image
