openapi: 3.0.3
info:
  title: ZTNet Statistics Rest API
  version: 1.0.0
  description: |
    Access the ZTNet Statistics API to get various statistics that can be used in 3rd party applications.
    Available from version v0.6.4.

    This interface is subject to a rate limit of 50 requests per minute to ensure service reliability.

servers:
  - url: https://ztnet.network/api/v1
    description: ZTNet API

components:
  securitySchemes:
    x-ztnet-auth:
      type: apiKey
      in: header
      name: x-ztnet-auth
      description: API key required for access

security:
  - x-ztnet-auth: []
paths:
  /stats:
    get:
      summary: Returns statistics for ztnet
      description: |
        Returns various statistics that can be used in 3rd party applications.  
        Available from version v0.6.4
      operationId: getAppStats
      responses:
        200:
          description: An object of statistics
          content:
            application/json:
              schema:
                $ref: '../../_schema/StatsSchema.yml#/StatsResponse'
              example:
                $ref: '../../_example/StatsExample.yml#/StatsExample'
        401:
          $ref: '../../_http_responses/Unauthorized.yml#/Unauthorized'
        429:
          $ref: '../../_http_responses/RateLimitExceeded.yml#/RateLimitExceeded'
        500:
          $ref: '../../_http_responses/InternalServerError.yml#/InternalServerError'