# This is a basic workflow to help you get started with Actions

#  ##########################################################
#      Add Swap File to DO!!  Important
#      https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-16-04
#
#############################################################
name: DIGTAL OCEAN

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [docker]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # services:
    #   postgres:
    #     image: postgres:12
    #     env:
    #       POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
    #       POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    #       POSTGRES_DB: simple_bank
    #     ports:
    #       - 5432:5432
    #     options: >-
    #       --health-cmd pg_isready
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: 'docker'
      - name: Create .env
        run: echo "POSTGRES_PASSWORD= " > .env
      - name: Run Build
        env:
          NODE_OPTIONS: '--max-old-space-size=1024'
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          CONNECTION_STRING: 'postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@${{ secrets.POSTGRES_HOST }}:$POSTGRES_PORT/$POSTGRES_DB?schema=public'
        run: docker-compose -f docker-compose-prod.yml up -d --build

      # - name:
      #   # Remove unused, dangling images
      #   run: docker rmi $(docker images -q -f dangling=true)

      # - name: Remove Unused Containers
      #   #https://gist.github.com/transcranial/be0f8f0d80e464f4032e
      #   run: docker rmi $(docker images -a | grep '<none>' | awk '{print $3}')
